[package]
name = "srd-editor"
version = "0.1.0"
edition = "2024"
publish = false
default-run = "srd-editor"

[dependencies]
imgui = { version = "0.12.0", features = ["docking", "tables-api"] }
imgui-winit-support = "0.13.0"
raw-window-handle = "0.6.2"
winit = { version = "0.30.12", default-features = false, features = ["rwh_06"] }
windows = { version = "0.62.2", features = [
    "Foundation_Numerics",
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D9",
    "Win32_Graphics_Gdi",
] }
windows-numerics = "0.3.1"
