use std::collections::BTreeMap;
use std::convert::TryInto;
use std::env;
use std::error::Error;
use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn Error>> {
    let mut arguments = env::args_os().skip(1);
    let input = arguments
        .next()
        .map(PathBuf::from)
        .ok_or("usage: package_simple_shaders <probe-output-dir> <output.rs>")?;
    let output = arguments
        .next()
        .map(PathBuf::from)
        .ok_or("usage: package_simple_shaders <probe-output-dir> <output.rs>")?;
    if arguments.next().is_some() {
        return Err("usage: package_simple_shaders <probe-output-dir> <output.rs>".into());
    }

    let manifest = fs::read_to_string(input.join("manifest.tsv"))?;
    let mut stages = BTreeMap::<String, (Option<Vec<u8>>, Option<Vec<u8>>)>::new();
    for line in manifest.lines().skip(1) {
        let columns = line.split('\t').collect::<Vec<_>>();
        if columns.len() != 5 || columns[4] != "ok" {
            return Err(format!("invalid or failed manifest row: {line}").into());
        }
        let key = columns[0];
        if key.len() != 18 || !key.bytes().all(|byte| (b'A'..=b'P').contains(&byte)) {
            return Err(format!("invalid Simple key: {key}").into());
        }
        let stage = columns[1];
        let bytes = fs::read(input.join(format!("SimpleShader{stage}_{key}.bin")))?;
        if bytes.len() % 4 != 0 {
            return Err(format!("{stage} bytecode for {key} is not DWORD aligned").into());
        }
        let entry = stages.entry(key.to_owned()).or_default();
        let replaced = match stage {
            "vs" => entry.0.replace(bytes),
            "ps" => entry.1.replace(bytes),
            _ => return Err(format!("invalid shader stage in row: {line}").into()),
        };
        if replaced.is_some() {
            return Err(format!("duplicate shader stage in row: {line}").into());
        }
    }
    if stages.len() != 82 || stages.values().any(|(vs, ps)| vs.is_none() || ps.is_none()) {
        return Err(format!("expected 82 complete shader pairs, found {}", stages.len()).into());
    }

    let mut unique_vs = Vec::<Vec<u8>>::new();
    let mut unique_ps = Vec::<Vec<u8>>::new();
    let mut entries = Vec::new();
    for (key, (vs, ps)) in stages {
        let vs_index = intern(&mut unique_vs, vs.unwrap());
        let ps_index = intern(&mut unique_ps, ps.unwrap());
        entries.push((key, vs_index, ps_index));
    }

    let mut source = String::from(
        "// Generated by tools/package_simple_shaders.rs from the exact 82-key\n\
         // Simple collection. Do not edit this file by hand.\n\n",
    );
    for (index, bytes) in unique_vs.iter().enumerate() {
        write_shader_array(&mut source, "VS", index, bytes)?;
    }
    for (index, bytes) in unique_ps.iter().enumerate() {
        write_shader_array(&mut source, "PS", index, bytes)?;
    }
    writeln!(
        source,
        "const GAME_SIMPLE_SHADER_KEYS: [[u8; CEYLON_SIMPLE_SHADER_KEY_LENGTH]; {}] = [",
        entries.len()
    )?;
    for (key, _, _) in &entries {
        writeln!(source, "    *b\"{key}\",")?;
    }
    source.push_str("];\n\n");
    writeln!(
        source,
        "const GAME_SIMPLE_SHADER_ENTRIES: [EmbeddedSimpleShaderEntry; {}] = [",
        entries.len()
    )?;
    for (key, vs, ps) in &entries {
        writeln!(
            source,
            "    EmbeddedSimpleShaderEntry {{ key: *b\"{key}\", vertex_shader: &VS_{vs:02}, pixel_shader: &PS_{ps:02} }},"
        )?;
    }
    source.push_str("];\n");
    fs::write(output, source)?;
    eprintln!(
        "packaged {} keys using {} unique VS and {} unique PS blobs",
        entries.len(),
        unique_vs.len(),
        unique_ps.len()
    );
    Ok(())
}

fn intern(blobs: &mut Vec<Vec<u8>>, bytes: Vec<u8>) -> usize {
    if let Some(index) = blobs.iter().position(|candidate| *candidate == bytes) {
        index
    } else {
        let index = blobs.len();
        blobs.push(bytes);
        index
    }
}

fn write_shader_array(
    output: &mut String,
    stage: &str,
    index: usize,
    bytes: &[u8],
) -> Result<(), std::fmt::Error> {
    writeln!(
        output,
        "const {stage}_{index:02}: [u32; {}] = [",
        bytes.len() / 4
    )?;
    for row in bytes.chunks(32) {
        output.push_str("    ");
        for (dword_index, dword) in row.chunks_exact(4).enumerate() {
            if dword_index != 0 {
                output.push(' ');
            }
            let value = u32::from_le_bytes(dword.try_into().unwrap());
            write!(output, "0x{value:08X},")?;
        }
        output.push('\n');
    }
    output.push_str("];\n\n");
    Ok(())
}
